[mypy]
python_version = 3.14
strict = True
warn_unused_configs = True

[mypy-PyQt6.*]
ignore_missing_imports = True

[mypy-pyqtgraph.*]
ignore_missing_imports = True

[mypy-serial.*]
ignore_missing_imports = True
